FROM alpine as builder

RUN apk add --no-cache \
    bash gcc make alpine-sdk coreutils git

WORKDIR /tmp
RUN git clone --depth=1 https://github.com/30mb1/CGI_server.git
RUN cd CGI_server && \
    sed -i 's/PATH_MAX/64/' main.c && \
    gcc -static -o cgi main.c utility.c && \
    chmod 0755 ./cgi

FROM sh-static
COPY --from=builder /tmp/CGI_server/cgi /