FROM alpine as builder

RUN apk add git \
 && git clone https://github.com/kkkgo/vlmcsd.git /tmp/vlmcsd \
 && chmod 0555 /tmp/vlmcsd/binaries/Linux/intel/static/*

FROM sh-static

COPY --from=builder /tmp/vlmcsd/binaries/Linux/intel/static/vlmcs-x64-musl-static /vlmcs
COPY --from=builder /tmp/vlmcsd/binaries/Linux/intel/static/vlmcsd-x86-musl-static /vlmcsd

EXPOSE 1688

CMD /vlmcsd -D -p /tmp/kmsd.pid -l /dev/stdout
